[general]
live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"


[window]
opacity = 0.9
blur = true 
padding.x = 10
padding.y = 5
dynamic_padding = true
level = "AlwaysOnTop"


decorations = "Full"
decorations_theme_variant = "Dark" 

[scrolling]
history = 100000


[font]
normal.family = "UbuntuMono Nerd Font Mono"
bold.family = "UbuntuMono Nerd Font Mono"
italic.family = "UbuntuMono Nerd Font Mono"

size=14

[selection]
save_to_clipboard = true

[cursor]
style.blinking = "On"
blink_timeout=15


[terminal]
shell.program = "/usr/bin/tmux"
shell.args = ["new-session", "-A", "-D", "-s", "main"]

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" }
]