# frozen_string_literal: true

source "https://rubygems.org"

gem "ruby-lsp"
gem "rubocop"
gem "rubocop-sorbet"
source "https://nexus.sbmt.io/repository/ruby-gems-sbermarket/" do
  gem "rubocop-fabrication"
  gem "sbmt-dev"
end
gem "pry-byebug"
